spring:
    application:
        name: usercenter
    # DataSource Config
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yupi
        username: root
        password: 123456
    session:
      timeout: 86400
server:
    port: 8080
    servlet:
        context-path: /api

mabatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        logic-delete-field: isDelete
        logic-delete-value: 1
        logic-not-delete-value: 0
